### ISSUE TITLE
Delayed actions ignore conditional logic

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-ninjaforms#9]
Message from a Pronamic Pay user:

> Pronamic Pay houdt geen rekening met ingestelde voorwaardes bij Ninja Forms.We willen namelijk acties uitvoeren nadat betaling is uitgevoerd, alleen nu voert hij alle acties uit die actief zijn gemarkeerd bij de acties. Terwijl er conditionele logica actief is. Zie ook log dump.

This is related to the https://ninjaforms.com/extensions/conditional-logic/ extensions → https://github.com/pronamic/ninja-forms-conditionals.

_Internal HelpScout ticket: https://secure.helpscout.net/conversation/2365232621/26169?folderId=1425710_

**Comment by remcotolsma** [comment]
It appears that this is a problem/limitation within the "Ninja Forms - Conditional Logic" plugin. The submitted data is no longer available after a successful payment and therefore the conditional logic can no longer be tested. The "Ninja Forms - Conditional Logic" plugin hooks into the `ninja_forms_submit_data` filter to parse the fields data. These fields data will be used later to test the conditional logic. When a payment provider notifies that the payment has been successful, there is no form submission and the `ninja_forms_submit_data` filter is not executed.

- https://github.com/pronamic/ninja-forms-conditionals/blob/b16979d5a8e71341477f90247789a9033d1cf72e/includes/Submission.php#L9
- https://github.com/pronamic/ninja-forms-conditionals/blob/b16979d5a8e71341477f90247789a9033d1cf72e/includes/Submission.php#L71-L79

```php
    public function parse_actions( $actions, $form_data )
    {
        // If we don't have a fieldsCollection (such as if this is a resume) skip this filter.
        if ( ! empty( $this->fieldsCollection ) ) {
            array_walk( $actions, array( $this, 'parse_action' ), $this->fieldsCollection );
        }

        return $actions;
    }
```

**Comment by rvdsteege** [comment]
> It appears that this is a problem/limitation within the "Ninja Forms - Conditional Logic" plugin.

Therefore, I think we can close this issue or do you want to reach out to the developers of the Ninja Forms - Conditional Logic plugin?

**Comment by remcotolsma** [comment]
Yes, I have not received a response from the customer either, let's close for now.
